// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4dNpzxFDtcxv1CDYnlNCWrxK6Kotg6Wo',
    appId: '1:416310773447:web:241ec16c44e2e424d4a0e2',
    messagingSenderId: '416310773447',
    projectId: 'united-bot-335423',
    authDomain: 'united-bot-335423.firebaseapp.com',
    storageBucket: 'united-bot-335423.appspot.com',
    measurementId: 'G-BW22QYDGT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfe5ky6nvzIwKWpycpbIFLmxZTBXSC1q4',
    appId: '1:416310773447:android:7c5b85684181f0e3d4a0e2',
    messagingSenderId: '416310773447',
    projectId: 'united-bot-335423',
    storageBucket: 'united-bot-335423.appspot.com',
  );
}
